routeEnhancers:
  News:
    type: Extbase
    extension: News
    plugin: Pi1
    # routes and aspects will follow here
  PageTypeSuffix:
    type: PageType
    default: .html
    map:
      sitemap.xml: 1533906435
